# Generated by Django 2.1.7 on 2019-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gitlab_url',
            field=models.URLField(default='gitlab.com'),
        ),
    ]
